{{- if .Values.secretData.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $v := .Values.secretData.data }}
  {{ $v.filename }}: |-
    {{ .Files.Get "configmaps/digitech-prod-environment-firebase-adminsdk-3091v-51a31e8dce.json" | b64enc }}
  {{- end }}
{{- end -}}
